
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost

development:
  <<: *default
  database: meals_management_app_development

test:
  <<: *default
  database: meals_management_app_test

production:
  <<: *default
  database: meals_management_app_production
  username: meals_management_app
  password: <%= ENV['BLOGS_APP_DATABASE_PASSWORD'] %>
