
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: mindfire
  host: localhost      

development:
  <<: *default
  database: blogs_app_development

test:
  <<: *default
  database: blogs_app_test

production:
  <<: *default
  database: blogs_app_production
  username: blogs_app
  password: <%= ENV['BLOGS_APP_DATABASE_PASSWORD'] %>
