
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: meals_management_app_development

test:
  <<: *default
  database: meals_management_app_test

production:
  <<: *default
  database: meals_management_app_production
  username: meals_management_app
  password: <%= ENV['BLOGS_APP_DATABASE_PASSWORD'] %>
