# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59dccc4d217ced692822e527c8ed0c87bd2244ccd1b511755af1abe7f203e39212babd4d750381c4a53e1b6f670e92b6f7c067a46d396a7bbbb0779462caa317

test:
  secret_key_base: 8ecea618c8c50c6c34c2f573f8ec5ce54d9b411a14a638db1f8e6ec2f8288a682d247ff3fc255b2ea972b9a7ab55ca514204e1199c9b3096e18ac91bd4175221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
